//
// Generated File!
//
// This file is Auto Generated by AssetsGenerator Plugin and should not be edited
// since it will be replaced by next plugin execution.
//

import Foundation
import UIKit

#if SWIFT_PACKAGE
private let resourceBundle = Foundation.Bundle.module
#else
private class ResourceBundleClass {}
private let resourceBundle = Foundation.Bundle(for: ResourceBundleClass.self)
#endif

public struct ImageAssetResource: Hashable {
    public var name: String
    public var bundle: Bundle
    
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

extension ImageResource {
    public init(asset: ImageAssetResource) {
        self.init(name: asset.name, bundle: asset.bundle)
    }
}

public struct ColorAssetResource: Hashable {
    public var name: String
    public var bundle: Bundle
    
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

extension ColorResource {
    public init(asset: ColorAssetResource) {
        self.init(name: asset.name, bundle: asset.bundle)
    }
}

@available(iOS 13.0, *)
extension UIImage {
    public convenience init(asset: ImageAssetResource) {
        self.init(named: asset.name, in: asset.bundle, with: nil)!
    }
}

@available(iOS 13.0, *)
extension UIColor {
    public convenience init(asset: ColorAssetResource) {
        self.init(named: asset.name, in: asset.bundle, compatibleWith: nil)!
    }
}

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension Image {
    public init(asset: ImageAssetResource) {
        self.init(asset.name, bundle: asset.bundle)
    }
}

@available(iOS 13.0, *)
extension Color {
    public init(asset: ColorAssetResource) {
        self.init(asset.name, bundle: asset.bundle)
    }
}

#endif

public extension ImageAssetResource {
	/// The "apple_maps" asset catalog image resource.
	static let appleMaps = Self.init(name: "apple_maps", bundle: resourceBundle)

	/// The "Swift_Script" asset catalog image resource.
	static let swiftScript = Self.init(name: "Swift_Script", bundle: resourceBundle)

	/// The "swiftui" asset catalog image resource.
	static let swiftui = Self.init(name: "swiftui", bundle: resourceBundle)

}

